apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::718567677502:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-BV6M1O2B7LLC
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-18T01:15:27Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "772"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: ed3017c2-78a4-4600-84dc-8c262c6b69b5
