apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::197850508634:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::197850508634:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-N98BJSN8UIE6
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-19T05:57:03Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "969"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 974f9e04-2533-4b2c-959c-8440e814eda1
